SELECT 
		cws.USERID as COL_ID,
        cws.USERID,
        cws.CODE,
        cws.NAME,
        cws.DOMAINID,
        cws.CREATEDBY,
        cws.CREATEDDATE,
        cws.MODIFIEDBY,
        cws.MODIFIEDDATE,
        cws.ACCESSSUBJECTID,
        cws.LOGIN,
        cws.LOGINTYPE,
        cws.SOURCE,
        cws.PROFILE,
        cws.STATUS,
        cws.ISLOCKEDOUT,
        cws.ISSYSTEM,
        cws.POSITION,
        cws.PHOTO,
        cws.EMAIL,
        cws.FIRSTNAME,
        cws.LASTNAME,
        cws.CITY,
        cws.STATE,
        cws.PHONE,
        cws.SUPERVISOR,
        cws.ID,
        cws.ACCODE,
        cws.ISDELETED,
        cws.EXTSYSID,
        cws.ISACTIVE
FROM   vw_PPL_CaseWorkersUsers cws    
WHERE  NVL(ISDELETED, 0) = 0 AND NVL(STATUS,0) = 0  AND NVL(ISLOCKEDOUT, 0) = 0 