SELECT     s.SESSIONID AS ID,
           s.SESSIONID AS SESSIONID,
           u.userid AS USERID,
           u.login AS LOGIN,
           u.name AS NAME,
           u.PROFILE AS PROFILE,
           up.EMAIL AS EMAIL,
		   s.CREATEDDATE as SESSION_LOGINDATE,
		   s.LASTACCESSTIME as SESSION_LASTACCESSTIME,
		   s.LOGOUTTIME as SESSION_LOGOUTDATE,
           s.EXPPERIOD AS EXPPERIOD,
           nvl2(s.LOGOUTTIME,TRUNC((s.LOGOUTTIME - s.LASTACCESSTIME) * 24 * 60 * 60),TRUNC((SYSDATE - s.LASTACCESSTIME) * 24 * 60 * 60)) SES_DURATION
FROM       @TOKEN_SYSTEMDOMAINUSER@.asf_user u
INNER JOIN @TOKEN_SYSTEMDOMAINUSER@.asf_accesssubject sub ON sub.ACCESSSUBJECTID = u.ACCESSSUBJECTID
INNER JOIN @TOKEN_SYSTEMDOMAINUSER@.asf_session s         ON sub.code = s.ACCESSSUBJECTID
INNER JOIN @TOKEN_SYSTEMDOMAINUSER@.user_profile up       ON up.USERID = u.userid
