SELECT u.*,
F_UTIL_GETDRTNFRMNOW(u.SESSION_LOGINDATE) as SESSION_LOGINDUR,
F_UTIL_GETDRTNFRMNOW(u.SESSION_LASTACCESSTIME) as SESSION_LASTACCESSDUR,
F_UTIL_GETDRTNFRMNOW(u.SESSION_LOGOUTDATE) as SESSION_LOGOUTDUR
FROM VW_PPl_UserSession u
where 1=1
<%= IfNotNull(":Login", " AND u.login = :Login ") %>
<%= IfNotNull(":Name", " AND lower(u.name) like '%'||lower(:Name)||'%' ") %>
<%= IfNotNull(":CaseWorker_Id", " AND USERID = (SELECT COL_USERID FROM TBL_PPL_CASEWORKER WHERE COL_ID = :CaseWorker_Id)") %>
<%= IfNotNull(":ISCURRENTUSER", " AND USERID = (SELECT USERID FROM VW_USERS WHERE ACCESSSUBJECTCODE = '@TOKEN_USERACCESSSUBJECT@')") %>
<%=IfNotNull("@SORT@", " ORDER BY @SORT@ @DIR@, 1")%>