DECLARE

  V_URL      NVARCHAR2(255);
  V_EXTENSION NVARCHAR2(255);
  V_DOC_ID   INTEGER;
  V_BATCHID  INTEGER;
  V_FOLDERID INTEGER;
  v_ISGLOBALRESOURCE NUMBER;

  --links
  V_CASETYPE_ID NUMBER;
  V_CASE_ID     NUMBER;
  V_TASK_ID     NUMBER;
  v_ExtParty_Id NUMBER;
  v_Team_Id     NUMBER;
  v_CW_Id       NUMBER;

BEGIN
  V_DOC_ID := 0;
  V_URL    := :DOC_URI;
  V_EXTENSION := SUBSTR(V_URL, INSTR(V_URL, '.', -1));

  BEGIN
    V_BATCHID := TO_NUMBER(:BATCH_NUMBER);
  EXCEPTION
    WHEN OTHERS THEN
      V_BATCHID := NULL;
  END;

  BEGIN
    V_FOLDERID := TO_NUMBER(:CALCPARENTID);
  EXCEPTION
    WHEN OTHERS THEN
      V_FOLDERID := -1;
  END;

  BEGIN
    v_ISGLOBALRESOURCE := TO_NUMBER(:ISGLOBALRESOURCE);
  EXCEPTION
    WHEN OTHERS THEN
      v_ISGLOBALRESOURCE := 0;
  END;

  BEGIN
    V_CASETYPE_ID := TO_NUMBER(:CASETYPE_ID);
  EXCEPTION
    WHEN OTHERS THEN
      V_CASETYPE_ID := NULL;
  END;

  BEGIN
    V_CASE_ID := TO_NUMBER(:CASE_ID);
  EXCEPTION
    WHEN OTHERS THEN
      V_CASE_ID := NULL;
  END;

  BEGIN
    V_TASK_ID := TO_NUMBER(:TASK_ID);
  EXCEPTION
    WHEN OTHERS THEN
      V_TASK_ID := NULL;
  END;

  BEGIN
    v_ExtParty_Id := TO_NUMBER(:EXTPARTY_ID);
  EXCEPTION
    WHEN OTHERS THEN
      v_ExtParty_Id := NULL;
  END;
  BEGIN
    v_Team_Id := TO_NUMBER(:TEAM_ID);
  EXCEPTION
    WHEN OTHERS THEN
      v_Team_Id := NULL;
  END;
  BEGIN
    v_CW_Id := TO_NUMBER(:CASEWORKER_ID);
  EXCEPTION
    WHEN OTHERS THEN
      v_CW_Id := NULL;
  END;

  INSERT INTO TBL_DOC_DOCUMENT
    (COL_ISFOLDER, COL_PARENTID, COL_URL, COL_NAME,COL_ISGLOBALRESOURCE)
  VALUES
    (0, V_FOLDERID,
     V_URL,
     'Scan Batch # ' || TO_CHAR(V_BATCHID),v_ISGLOBALRESOURCE)
  RETURNING COL_ID INTO V_DOC_ID;

  IF V_CASETYPE_ID IS NOT NULL THEN
    INSERT INTO TBL_DOC_DOCCASETYPE
      (COL_DOCCSETYPEDOC, COL_DOCCSETYPETYPE)
    VALUES
      (V_DOC_ID, V_CASETYPE_ID);
  END IF;

  IF V_CASE_ID IS NOT NULL THEN
    INSERT INTO TBL_DOC_DOCCASE
      (COL_DOCCASEDOCUMENT, COL_DOCCASECASE)
    VALUES
      (V_DOC_ID, V_CASE_ID);
  END IF;

  IF V_TASK_ID IS NOT NULL THEN
    INSERT INTO TBL_DOC_DOCTASK
      (COL_DOCTASKDOCUMENT, COL_DOCTASKTASK)
    VALUES
      (V_DOC_ID, V_TASK_ID);
  END IF;

  IF v_ExtParty_Id IS NOT NULL THEN
    INSERT INTO tbl_doc_docExtPrt
      (col_docextprtdoc, col_docextprtextprt)
    VALUES
      (V_DOC_ID, v_ExtParty_Id);
  END IF;

  IF v_Team_Id IS NOT NULL THEN
    INSERT INTO tbl_doc_docTeam (col_docteamdoc, col_docteamteam) VALUES (V_DOC_ID, v_Team_Id);
  END IF;

  IF v_CW_Id IS NOT NULL THEN
    INSERT INTO tbl_doc_DocCW (col_doccwdoc, col_doccwcw) VALUES (V_DOC_ID, v_CW_Id);
  END IF;

  UPDATE TBL_DOC_DOCUMENT
     SET COL_NAME = COL_NAME || ' Doc # ' || TO_CHAR(V_DOC_ID) || V_EXTENSION
   WHERE COL_ID = V_DOC_ID;

  :DOC_ID := V_DOC_ID;
END;