SELECT
    max(DOC.ID) AS ID
FROM VW_DOC_DOCUMENTS DOC
WHERE 
    ISFOLDER = 0 
    AND DOC.CALCPARENTID = :PARENTID
    AND (:CASETYPE_ID IS NULL OR DOC.CASETYPEID = :CASETYPE_ID)
    AND (:CASE_ID IS NULL
        OR (:TASK_ID IS NOT NULL
        OR DOC.CASEID = :CASE_ID
        OR DOC.CASETYPEID = (SELECT COL_CASEDICT_CASESYSTYPE
                    FROM TBL_CASE
                    WHERE COL_ID = :CASE_ID)
        )
    )
    AND (:TASK_ID IS NULL OR DOC.TASKID = :TASK_ID)
    AND (:EXTPARTY_ID IS NULL OR DOC.EXTPARTYID = :EXTPARTY_ID)
    AND (:TEAM_ID IS NULL OR DOC.TEAMID = :TEAM_ID)
    AND (:CASEWORKER_ID IS NULL OR DOC.CASEWORKERID = :CASEWORKER_ID)
    AND (:ISGLOBALRESOURCE IS NULL OR NVL(DOC.ISGLOBALRESOURCE,0) = :ISGLOBALRESOURCE)