SELECT
    DOC.ID AS BRANCHID,
    REPLACE(SYS_CONNECT_BY_PATH(
     case when DOC.ISFOLDER = 1 then
    DOC.NAME||'_'||DOC.ID
    else
    DOC.NAME
    end
    ,'/'),'-','')  AS BRANCHPATH,
    DOC.URL AS DOCUMENTURL,
    DOC.ISFOLDER AS ISFOLDER
FROM (
    SELECT -1 AS ID,
        0 AS CALCPARENTID,
        1 AS ISFOLDER,
        NULL AS ISGLOBALRESOURCE,
        CAST('Home folder' AS NVARCHAR2(255)) AS NAME,
        NULL AS URL
    FROM DUAL
        UNION ALL
    SELECT 
        DOC.ID AS ID,
        DOC.CALCPARENTID AS CALCPARENTID,
        DOC.ISFOLDER AS ISFOLDER,
        NVL(DOC.ISGLOBALRESOURCE,0) AS ISGLOBALRESOURCE,
        DOC.NAME AS NAME,
        DOC.URL AS URL
    FROM VW_DOC_DOCUMENTS DOC
    WHERE (:CASETYPE_ID IS NULL OR DOC.CASETYPEID = :CASETYPE_ID)
    AND (:CASE_ID IS NULL
        OR (:TASK_ID IS NOT NULL
            OR DOC.CASEID = :CASE_ID
            OR DOC.CASETYPEID = (SELECT COL_CASEDICT_CASESYSTYPE
                                FROM TBL_CASE
                                WHERE COL_ID = :CASE_ID)
            )
        )
    AND (:TASK_ID IS NULL OR DOC.TASKID = :TASK_ID)
    AND (:EXTPARTY_ID IS NULL OR DOC.EXTPARTYID = :EXTPARTY_ID)
    AND (:TEAM_ID IS NULL OR DOC.TEAMID = :TEAM_ID)
    AND (:CASEWORKER_ID IS NULL OR DOC.CASEWORKERID = :CASEWORKER_ID)
    AND (:ISGLOBALRESOURCE IS NULL OR NVL(DOC.ISGLOBALRESOURCE,0) = :ISGLOBALRESOURCE)) DOC

START WITH DOC.ID = NVL(:FOLDERID,-1) 
CONNECT BY PRIOR DOC.ID = DOC.CALCPARENTID