select dse.SlaEventId as SlaEventId,
	   dse.SlaEventId as Col_Id,
       dse.SlaTaskId as SlaTaskId,
       dse.DateEventTaskId as DateEventTaskId,
       dse.SlaTimestampValue as SlaTimestampValue,
       dse.SlaEventTypeCode as SlaEventTypeCode,
       dse.SlaEventIntervalDS as SlaEventIntervalDS,
       dse.SlaEventIntervalYM as SlaEventIntervalYM,
       dse.SlaEventTypeIntervalDS as SlaEventTypeIntervalDS,
       dse.SlaEventTypeIntervalYM as SlaEventTypeIntervalYM,
       dse.SlaDateValue as SlaDateValue,
       dse.SlaExpDate as SlaExpDate,
       (dse.SlaExpDate - cast(sysdate as timestamp)) * 24 * 3600 as SlaSecondsLeft,
       (case when SlaMonths > 0 then SlaMonths else 0 end) as SlaMonths,
       (case when extract(day from SlaDaysFrom) > 0 then extract(day from SlaDaysFrom) else 0 end) as SlaDays,
       (case when extract(hour from SlaDaysFrom) > 0 then extract(hour from SlaDaysFrom) else 0 end) as SlaHours,
       (case when extract(minute from SlaDaysFrom) > 0 then extract(minute from SlaDaysFrom) else 0 end)as SlaMinutes,
       (case when extract(second from SlaDaysFrom) > 0 then extract(second from SlaDaysFrom) else 0 end) as SlaSeconds
from (select SlaEventId,
       SlaTaskId,
       DateEventTaskId,
       SlaTimestampValue,
       SlaEventTypeCode,
       SlaEventIntervalDS,
       SlaEventIntervalYM,
       SlaEventTypeIntervalDS,
       SlaEventTypeIntervalYM,
       SlaDateValue,
       SlaExpDate,
       trunc(months_between(SlaExpDate, sysdate)) as SlaMonths,
       SlaExpDate - add_months(sysdate, trunc(months_between(SlaExpDate, sysdate))) as SlaDaysFrom,
       row_number() over (partition by SlaTaskId order by SlaExpDate asc) as rownumber
       from vw_dcm_deadlineslaevent) dse
       where dse.SlaTaskId = dse.DateEventTaskId and dse.rownumber = 1