SELECT ID, CASEID, SUMMARY
FROM VW_DCM_SIMPLECASECTACCACHELST
WHERE ID IN (
SELECT CASEID
FROM vw_DCM_SimpleTask tv
LEFT JOIN  vw_dcm_taskslaprimaryevent6 tse  ON tse.nexttaskid = tv.id AND tse.prevtaskid = tv.id
WHERE tv.TASKSTATE_ISFINISH = 0 AND tse.PREVSLADATETIME IS NOT NULL
GROUP BY CASEID)
