DECLARE 
	v_CaseWorkerID INTEGER; 
	v_ITEMS sys_refcursor;
BEGIN 
	--get my Case Worker ID
	SELECT id 
	INTO v_CaseWorkerID
	FROM vw_ppl_caseworkersusers 
	WHERE  accode = Sys_context('CLIENTCONTEXT', 'AccessSubject');
	
	
	--get the workbaskets of teams caseworker is part of
	OPEN v_ITEMS FOR SELECT WB_ID FROM 
		(SELECT COL_ID as WB_ID
		FROM TBL_PPL_WORKBASKET
		WHERE COL_WORKBASKETTEAM IN (		
			SELECT COL_TBL_PPL_TEAM
			FROM TBl_CASEWORKERTEAM
			WHERE COL_TM_PPL_CASEWORKER = 1
		)
		UNION
		SELECT COL_MAP_WB_TM_WORKBASKET as WB_ID
		FROM TBL_MAP_WORKBASKETTEAM
		WHERE COL_MAP_WB_TM_TEAM IN (		
			SELECT COL_TBL_PPL_TEAM
			FROM TBl_CASEWORKERTEAM
			WHERE COL_TM_PPL_CASEWORKER = 1
		)

		--get the workbaskets of skills caseworker is part of
		UNION
		SELECT COL_ID as WB_ID
		FROM TBL_PPL_WORKBASKET
		WHERE COL_WORKBASKETSKILL IN (		
			SELECT COL_TBL_PPL_SKILL
			FROM TBl_CASEWORKERSKILL
			WHERE COL_SK_PPL_CASEWORKER = 1
		)
		UNION
		SELECT COL_MAP_WS_WORKBASKET as WB_ID
		FROM TBL_MAP_WORKBASKETSKILL
		WHERE COL_MAP_WS_SKILL IN (		
			SELECT COL_TBL_PPL_SKILL
			FROM TBl_CASEWORKERSKILL
			WHERE COL_SK_PPL_CASEWORKER = 1
		)
		UNION
		--get the workbaskets of business roles caseworker is part of
		SELECT COL_ID as WB_ID
		FROM TBL_PPL_WORKBASKET
		WHERE COL_WORKBASKETBUSINESSROLE IN (		
			SELECT COL_TBL_PPL_BUSINESSROLE
			FROM TBl_CASEWORKERBUSINESSROLE
			WHERE COL_BR_PPL_CASEWORKER = 1
		)
		UNION
		SELECT COL_MAP_WB_BR_WORKBASKET as WB_ID
		FROM TBL_MAP_WORKBASKETBUSNESSROLE
		WHERE COL_MAP_WB_WR_BUSINESSROLE IN (		
			SELECT COL_TBL_PPL_BUSINESSROLE
			FROM TBl_CASEWORKERBUSINESSROLE
			WHERE COL_BR_PPL_CASEWORKER = 1
		)
		--get the workbaskets tied to a caseworker's shared baskets
		UNION
		SELECT COL_MAP_WB_CW_WORKBASKET as WB_ID
		FROM TBL_MAP_WORKBASKETCASEWORKER
		WHERE COL_MAP_WB_CW_CASEWORKER = 1
	);
    
    return v_ITEMS;

EXCEPTION 
	WHEN no_data_found THEN 
	  return v_ITEMS;
END; 

