SELECT t.*, t.COL_ID AS InstID, a.Code AS ActivityCode, w.Code AS WorkflowCode, ao.Code AS AccessObjectCode FROM
(
SELECT 0 AS LEV, 0 AS TYPE, wi.*
FROM TBL_CW_WORKITEM wi
WHERE wi.COL_INSTANCEID = :InstanceId

UNION ALL

SELECT LEVEL AS LEV, 1 AS TYPE, wi.*
FROM TBL_CW_WORKITEM wi
WHERE wi.COL_INSTANCEID <> :InstanceId
START WITH wi.COL_INSTANCEID = :InstanceId
CONNECT BY PRIOR wi.COL_ID = wi.COL_REFPARENTID

UNION ALL

SELECT LEVEL AS LEV, 2 AS TYPE, wi.*
FROM TBL_CW_WORKITEM wi
WHERE wi.COL_INSTANCEID <> :InstanceId
START WITH wi.COL_INSTANCEID = :InstanceId
CONNECT BY PRIOR wi.COL_REFPARENTID = wi.COL_ID
) t
INNER JOIN @TOKEN_SYSTEMDOMAINUSER@.WF_ACTIVITY a ON (a.Code = t.COL_ACTIVITY)
INNER JOIN @TOKEN_SYSTEMDOMAINUSER@.WF_WORKFLOW w ON (a.WorkflowId = w.WorkflowId AND w.EnvId = '@TOKEN_DOMAIN@')
INNER JOIN @TOKEN_SYSTEMDOMAINUSER@.ASF_ACCESSOBJECT ao ON (a.AccessObjectId = ao.AccessObjectId)