SELECT
    LD.COL_ID AS ID,
    LD.COL_NAME AS NAME,
    LD.COL_CODE AS CODE,
    F_GETNAMEFROMACCESSSUBJECT(LD.COL_CREATEDBY) AS CREATEDBY_NAME,
    F_UTIL_GETDRTNFRMNOW(LD.COL_CREATEDDATE) AS CREATEDDURATION,
    F_GETNAMEFROMACCESSSUBJECT(LD.COL_MODIFIEDBY) AS MODIFIEDBY_NAME,
    F_UTIL_GETDRTNFRMNOW(LD.COL_MODIFIEDDATE) AS MODIFIEDDURATION
FROM TBL_DICT_LINKDIRECTION LD
WHERE (:ID IS NULL OR LD.COL_ID = :ID)
<%=IfNotNull("@SORT@", " order by @SORT@ @DIR@, 1")%>