SELECT rownum as RN123,
       ui.COL_ID AS ID,
       ui.COL_NAME AS NAME,
       ui.COL_CODE AS CODE,
       ui.COL_ISHIDDEN AS ISHIDDEN,
       ui.COL_CONFIG AS CONFIG,
       ui.COL_PROCESSORCODE AS PROCESSORCODE,
       NVL(ui.COL_PARENTID, '0') AS PARENTID,
       ui.COL_TITLE AS TITLE,
       ui.COL_UIELEMENTORDER AS UIELEMENTORDER,
       ui.COL_ISDELETED AS ISDELETED,
       ui.COL_DESCRIPTION AS DESCRIPTION,
       (CASE
           WHEN DICT_CASESYSTYPE.COL_NAME IS NOT NULL THEN DICT_CASESYSTYPE.COL_NAME
           WHEN DICT_TASKSYSTYPE.col_Name IS NOT NULL THEN DICT_TASKSYSTYPE.col_Name
           WHEN DICT_CASETRANSITION.col_name IS NOT NULL THEN DICT_CASETRANSITION.col_name
           WHEN DICT_TASKTRANSITION.col_Name IS NOT NULL THEN DICT_TASKTRANSITION.col_Name
           ELSE ui.COL_NAME
        END)
          AS CALCULATEDNAME,
       f_getNameFromAccessSubject(ui.col_createdBy) AS CreatedBy_Name,
       f_UTIL_getDrtnFrmNow(ui.col_createdDate) AS CreatedDuration,
       f_getNameFromAccessSubject(ui.col_modifiedBy) AS ModifiedBy_Name,
       f_UTIL_getDrtnFrmNow(ui.col_modifiedDate) AS ModifiedDuration,
       --    CASE TYPE
       DICT_CASESYSTYPE.COL_ID AS CaseSysType_Id,
       DICT_CASESYSTYPE.COL_NAME AS CaseSysType_Name,
       DICT_CASESYSTYPE.COL_CODE AS CaseSysType_Code,
       --    TASK TYPE
       DICT_TASKSYSTYPE.COL_ID AS TaskSysType_Id,
       DICT_TASKSYSTYPE.COL_NAME AS TaskSysType_Name,
       DICT_TASKSYSTYPE.COL_CODE AS TaskSysType_Code,
       --    UIELEMENT TYPE
       t.COL_ID AS UIElementType_Id,
       t.COL_NAME AS UIElementType_Name,
       t.COL_CODE AS UIElementType_Code,
       --    CASE TRANSITION
       DICT_CASETRANSITION.COL_ID AS CASETRANSITION_ID,
       DICT_CASETRANSITION.COL_NAME AS CaseTransition_Name,
       DICT_CASETRANSITION.COL_CODE AS CaseTransition_Code,
       --    TASK TRANSITION
       DICT_TASKTRANSITION.COL_ID AS TaskTransition_Id,
       DICT_TASKTRANSITION.COL_NAME AS TaskTransition_Name,
       DICT_TASKTRANSITION.COL_CODE AS TaskTransition_Code
  FROM TBL_FOM_UIELEMENT ui
       LEFT JOIN TBL_FOM_UIELEMENTTYPE t
          ON (t.col_id = ui.COL_UIELEMENTUIELEMENTTYPE)
       LEFT JOIN TBL_DICT_CASESYSTYPE DICT_CASESYSTYPE
          ON (DICT_CASESYSTYPE.COL_ID = ui.COL_UIELEMENTCASESYSTYPE)
       LEFT JOIN TBL_DICT_TASKSYSTYPE DICT_TASKSYSTYPE
          ON (DICT_TASKSYSTYPE.COL_ID = ui.COL_UIELEMENTTASKSYSTYPE)
       LEFT JOIN TBL_DICT_CASETRANSITION DICT_CASETRANSITION
          ON DICT_CASETRANSITION.COL_ID = ui.COL_UIELEMENTCASETRANSITION
       LEFT JOIN TBL_DICT_TASKTRANSITION DICT_TASKTRANSITION
          ON DICT_TASKTRANSITION.COL_ID = ui.COL_UIELEMENTTASKTRANSITION
 WHERE (:UserEditable IS NULL OR (:UserEditable IS NOT NULL AND NVL(ui.COL_USEREDITABLE, 0) = :UserEditable))
       AND (LOWER(:CODE) IS NULL OR (LOWER(:CODE) IS NOT NULL AND LOWER(ui.COL_CODE) = LOWER(:CODE)))
       AND (:ID IS NULL OR (:ID IS NOT NULL AND ui.COL_ID = :ID))
       AND (:IsDeleted IS NULL OR (:IsDeleted IS NOT NULL AND NVL(ui.COL_ISDELETED, 0) = :IsDeleted))
       AND (NVL(:ShowHidden, 0) = 1 OR NVL(UI.COL_UIELEMENTPAGE, 0) = 0)
<%=Sort("@SORT@","@DIR@")%>