SELECT o.ID, o.CODE, o.NAME, o.TYPE
  FROM (SELECT RULEID AS ID, CODE AS CODE, NAME AS NAME, 'RULE' AS TYPE, COMPONENTID AS COMPONENTID
          FROM @TOKEN_SYSTEMDOMAINUSER@.CONF_RULE
          WHERE 1 = 1
          <%=IfNotNull(":APTags", " AND RULEID IN (SELECT tob.OBJECTID FROM @TOKEN_SYSTEMDOMAINUSER@.CONF_TAGOBJECT tob INNER JOIN @TOKEN_SYSTEMDOMAINUSER@.CONF_TAG t ON t.TAGID = tob.TAGID INNER JOIN (select to_char(regexp_substr(:APTags,'[[:'||'alnum:]_]+', 1, level)) AS tag_code From dual connect by dbms_lob.getlength(regexp_substr(:APTags, '[[:'||'alnum:]_]+', 1, level)) > 0) xtag ON xtag.tag_code = t.code WHERE tob.Type = 7)")%>
        UNION ALL
        SELECT PAGEID AS ID, CODE AS CODE, NAME AS NAME, 'PAGE' AS TYPE, COMPONENTID AS COMPONENTID
          FROM @TOKEN_SYSTEMDOMAINUSER@.CONF_NAVPAGE
        UNION ALL
        SELECT TAGID AS ID, CODE AS CODE, NAME AS NAME, 'TAG' AS TYPE, COMPONENTID AS COMPONENTID
          FROM @TOKEN_SYSTEMDOMAINUSER@.CONF_TAG) o
 INNER JOIN @TOKEN_SYSTEMDOMAINUSER@.CONF_VERSION v
    ON o.COMPONENTID = v.COMPONENTID
 INNER JOIN @TOKEN_SYSTEMDOMAINUSER@.CONF_ENVIRONMENT e
    ON v.VERSIONID = e.DEPVERSIONID
 WHERE e.code = '@TOKEN_DOMAIN@'
   <%=IfNotNull(":IsRule", " AND o.TYPE = 'RULE'")%>
   <%=IfNotNull(":IsPage", " AND o.TYPE = 'PAGE'")%>
   <%=IfNotNull(":IsTag", " AND o.TYPE = 'TAG'")%>
<%=IfNotNull("@SORT@", " ORDER BY @SORT@ @DIR@, 1")%>