SELECT 
	rp.RULEPARAMETERID AS ID, 
	rp.RULEID AS RULEID, 
	rp.CODE AS CODE, 
	rp.NAME AS NAME
 FROM @TOKEN_SYSTEMDOMAINUSER@.CONF_RULEPARAMETER rp
 INNER JOIN @TOKEN_SYSTEMDOMAINUSER@.CONF_RULE r ON r.RULEID = rp.RULEID
 INNER JOIN @TOKEN_SYSTEMDOMAINUSER@.CONF_VERSION v ON r.COMPONENTID = v.COMPONENTID
 INNER JOIN @TOKEN_SYSTEMDOMAINUSER@.CONF_ENVIRONMENT e ON v.VERSIONID = e.DEPVERSIONID
 WHERE e.code = '@TOKEN_DOMAIN@'
   AND (:Id IS NULL OR (:Id IS NOT NULL AND rp.RULEPARAMETERID = :Id))
   AND (:RuleId IS NULL OR (:RuleId IS NOT NULL AND rp.RULEID = :RuleId))

<%= IfNotNull(":ONLYINPUT", " AND rp.BEHAVIORTYPE IN (1,5)") %>       
   
<%=Sort("@SORT@","@DIR@")%>
