 SELECT domObjChild.COL_ID AS Id,
        domObjChild.COL_NAME AS Name,
        domObjChild.COL_CODE AS Code,
        (SELECT sc.COL_ID AS SEARCHCONFIGID
        FROM TBL_DOM_OBJECT do
            LEFT JOIN TBL_FOM_OBJECT fo ON do.COL_DOM_OBJECTFOM_OBJECT = fo.COL_ID
            LEFT JOIN TBL_SOM_CONFIG sc ON fo.COL_ID = sc.COL_SOM_CONFIGFOM_OBJECT
        WHERE do.COL_ID = domObjChild.COL_ID AND ROWNUM = 1) AS SEARCHCONFIGID
   FROM TBL_DOM_OBJECT domObjPar
   LEFT JOIN TBL_DOM_RELATIONSHIP domRel
     ON domObjPar.COL_ID = domRel.COL_PARENTDOM_RELDOM_OBJECT
  INNER JOIN TBL_DOM_OBJECT domObjChild
     ON domObjChild.COL_ID = domRel.COL_CHILDDOM_RELDOM_OBJECT
  WHERE CONNECT_BY_ISCYCLE = 0
    AND (domRel.COL_PARENTDOM_RELDOM_OBJECT = :ParentObj AND LEVEL = 1)
  START WITH domObjPar.COL_ID = :ParentObj
CONNECT BY NOCYCLE PRIOR domObjChild.COL_ID = domObjPar.COL_ID
<%=Sort("@SORT@","@DIR@")%>