SELECT o.COL_ID AS ID,
    o.COL_NAME AS NAME,
    o.COL_CODE AS CODE,
    o.COL_UCODE AS UCODE,
    o.COL_ISROOT AS ISROOT,
    o.COL_ISSHARABLE AS ISSHARABLE,
    o.COL_DOM_OBJECTFOM_OBJECT AS FOM_OBJECTID,
    o.COL_DOM_OBJECTDOM_MODEL AS DOM_MODELID,
    F_GETNAMEFROMACCESSSUBJECT(o.COL_CREATEDBY) AS CREATEDBY_NAME,
    F_UTIL_GETDRTNFRMNOW(o.COL_CREATEDDATE) AS CREATEDDURATION,
    F_GETNAMEFROMACCESSSUBJECT(o.COL_MODIFIEDBY) AS MODIFIEDBY_NAME,
    F_UTIL_GETDRTNFRMNOW(o.COL_MODIFIEDDATE) AS MODIFIEDDURATION
FROM TBL_DOM_OBJECT o
    LEFT JOIN TBL_DOM_MODEL m ON o.COL_DOM_OBJECTDOM_MODEL = m.COL_ID
    LEFT JOIN TBL_MDM_MODEL mm ON m.COL_DOM_MODELMDM_MODEL = mm.COL_ID
WHERE (:ID IS NULL OR o.COL_ID = :ID)
    AND mm.col_id = :OBJECTID
    AND o.COL_TYPE NOT IN ('parentBusinessObject', 'referenceObject')
<%=IfNotNull("@SORT@", " ORDER BY @SORT@ @DIR@, 1")%>