SELECT ue.COL_ID AS ID,
       ue.COL_UIELEMENTFORM AS FORMID,
       ue.COL_JSONDATA AS JSONDATA,
       ue.COL_POSITIONINDEX AS POSITIONINDEX,
       ue.COL_REGIONID AS REGIONID,
       ue.COL_DESCRIPTION AS DESCRIPTION,
       'element_' || TO_CHAR(ue.COL_ID) AS CODE,
       ue.COL_ISEDITABLE AS ISEDITABLE,
       ue.COL_PARENTID AS PARENTID,
       ue.COL_FOM_UIELEMENTSOM_CONFIG AS SOMCONFIGID,
       ue.COL_UIELEMENTOBJECT AS DOMOBJECTID,
       ue.COL_RULEVISIBILITY AS RULEVISIBILITY,
       (SELECT LIST_COLLECT (CAST(COLLECT(TO_CHAR(ue_attr.COL_DOM_ATTRIBUTE_ID) ORDER BY TO_CHAR(ue_attr.COL_DOM_ATTRIBUTE_ID)) AS SPLIT_TBL),',',1)
        FROM TBL_UIELEMENT_DOM_ATTRIBUTE ue_attr
        WHERE ue_attr.COL_FOM_UIELEMENT_ID = ue.COL_ID) AS ATTRIBUTES
FROM TBL_FOM_UIELEMENT ue
WHERE    ue.COL_UIELEMENTFORM = :FormId
ORDER BY ue.COL_REGIONID, ue.COL_POSITIONINDEX ASC