SELECT obj.COL_NAME AS OBJECTNAME,
       obj.COL_CODE AS OBJECTCODE,
       NVL (obj.COL_APICODE, obj.COL_CODE) AS APICODE,
       f_MDM_getXMLAttributes(FOMObjectId => obj.COL_ID) AS ATTRIBUTES
  FROM tbl_FOM_OBJECT obj
 WHERE obj.COL_CODE = :PARENTOBJECT