SELECT
    MDM_MODEL.COL_ID AS ID,
    MDM_MODEL.COL_CODE AS CODE,
    MDM_MODEL.COL_NAME AS NAME,
    MDM_MODEL.COL_DESCRIPTION AS DESCRIPTION,
    MDM_MODEL.COL_ISDELETED AS ISDELETED,
    MDM_MODEL.COL_USEDFOR AS USEDFOR,
    FOM_OBJECT.COL_ID AS OBJECTID,
    SOM_MODEL.COL_ID AS SOMMODELID,
    DOM_MODEL.COL_ID AS DOMMODELID,
    F_GETNAMEFROMACCESSSUBJECT(MDM_MODEL.COL_CREATEDBY) AS CREATEDBY_NAME,
    F_UTIL_GETDRTNFRMNOW(MDM_MODEL.COL_CREATEDDATE) AS CREATEDDURATION,
    F_GETNAMEFROMACCESSSUBJECT(MDM_MODEL.COL_MODIFIEDBY) AS MODIFIEDBY_NAME,
    F_UTIL_GETDRTNFRMNOW(MDM_MODEL.COL_MODIFIEDDATE) AS MODIFIEDDURATION
   <%=IfNotNull("@ISCONFIG@", ",dbms_xmlgen.CONVERT(MDM_MODEL.COL_CONFIG) AS CONFIG")%>
FROM TBL_MDM_MODEL MDM_MODEL
    LEFT JOIN TBL_FOM_OBJECT FOM_OBJECT ON FOM_OBJECT.COL_ID = MDM_MODEL.COL_MDM_MODELFOM_OBJECT
    LEFT JOIN tbl_SOM_Model SOM_MODEL ON SOM_MODEL.COL_SOM_MODELMDM_MODEL = MDM_MODEL.COL_ID
    LEFT JOIN TBL_DOM_MODEL DOM_MODEL ON DOM_MODEL.COL_DOM_MODELMDM_MODEL = MDM_MODEL.COL_ID
WHERE
        (:MODEL_ID IS NULL OR MDM_MODEL.COL_ID = :MODEL_ID)
    AND (:USEDFOR IS NULL OR MDM_MODEL.COL_USEDFOR = :USEDFOR)
    AND (:ISDELETED IS NULL OR MDM_MODEL.COL_ISDELETED = :ISDELETED)
    AND (
        :UNIFIED_SEARCH IS NULL
        OR LOWER(MDM_MODEL.COL_CODE) LIKE F_UTIL_TOWILDCARDS(:UNIFIED_SEARCH)
        OR LOWER(MDM_MODEL.COL_NAME) LIKE F_UTIL_TOWILDCARDS(:UNIFIED_SEARCH)
        OR LOWER(MDM_MODEL.COL_DESCRIPTION) LIKE F_UTIL_TOWILDCARDS(:UNIFIED_SEARCH)
    )
    AND (:PSEARCH IS NULL OR (lower(MDM_MODEL.COL_NAME) like lower('%' || :PSEARCH || '%')))
<%=IfNotNull("@SORT@", " ORDER BY @SORT@ @DIR@, 1")%>