SELECT sc.COL_ID AS ID,
    sc.COL_NAME AS NAME,
    so.COL_ID AS SOMOBJECTID,
    sc.COL_CODE AS CODE,    
    r.COL_ID AS FORMID, 
    r.COL_NAME AS FORMNAME
FROM TBL_SOM_CONFIG sc
LEFT JOIN TBL_SOM_OBJECT so ON so.COL_SOM_OBJECTFOM_OBJECT = sc.COL_SOM_CONFIGFOM_OBJECT
LEFT JOIN TBL_FOM_OBJECT fo ON fo.COL_ID = sc.COL_SOM_CONFIGFOM_OBJECT
LEFT JOIN TBL_DOM_OBJECT do ON fo.COL_ID = do.COL_DOM_OBJECTFOM_OBJECT
LEFT JOIN (SELECT f.COL_ID, f.COL_NAME, f.COL_MDM_FORMDOM_OBJECT FROM TBL_MDM_FORM f WHERE f.COL_MDM_FORMDOM_OBJECT = :ID AND ROWNUM <= 1) r 
    ON r.COL_MDM_FORMDOM_OBJECT = do.COL_ID
WHERE do.COL_ID = :ID