SELECT f.COL_ID AS ID,
       f.COL_NAME AS NAME,
       f.COL_CODE AS CODE,
       f.COL_DESCRIPTION AS DESCRIPTION,
       f.COL_ISDELETED AS ISDELETED,
       f.COL_MDM_FORMDOM_OBJECT AS OBJECTID,
       o.col_name AS OBJECTNAME,
       f.COL_INSERTDOMOBJECTID AS INSERTDOMOBJECTID,
       f.COL_UPDATEDOMOBJECTID AS UPDATEDOMOBJECTID,
       f.COL_BUSINESSOBJECT AS BUSINESSOBJECT,
       F_GETNAMEFROMACCESSSUBJECT (f.COL_CREATEDBY) AS CREATEDBY_NAME,
       F_UTIL_GETDRTNFRMNOW (f.COL_CREATEDDATE) AS CREATEDDURATION,
       F_GETNAMEFROMACCESSSUBJECT (f.COL_MODIFIEDBY) AS MODIFIEDBY_NAME,
       F_UTIL_GETDRTNFRMNOW (f.COL_MODIFIEDDATE) AS MODIFIEDDURATION,
       fo.COL_CODE AS OBJECTCODE,
       dbms_xmlgen.CONVERT( f.col_formrule) AS FORMRULE,
       f_MDM_getObjectPath(FOMObjectId => o.col_dom_objectfom_object) as OBJECTPATH
  FROM TBL_MDM_FORM f
       LEFT JOIN TBL_DOM_OBJECT o ON f.COL_MDM_FORMDOM_OBJECT = o.COL_ID
       LEFT JOIN TBL_DOM_MODEL m  ON o.COL_DOM_OBJECTDOM_MODEL = m.COL_ID
       LEFT JOIN TBL_MDM_MODEL mm ON m.COL_DOM_MODELMDM_MODEL = mm.COL_ID
       LEFT JOIN TBL_SOM_OBJECT so ON so.col_som_objectfom_object = o.col_dom_objectfom_object
       INNER JOIN TBL_FOM_OBJECT fo ON fo.COL_ID = o.COL_DOM_OBJECTFOM_OBJECT
 WHERE     (:ID IS NULL OR f.COL_ID = :ID)
       AND (:MDMMODELID IS NULL OR mm.COL_ID = :MDMMODELID)
       AND (:OBJECTID IS NULL OR (:OBJECTID = o.COL_ID))
       AND (:SOMOBJECTID IS NULL OR (so.COL_ID = :SOMOBJECTID))
       AND (:OBJECTCODE IS NULL OR upper(so.COL_CODE) = upper(:OBJECTCODE))
<%=IfNotNull("@SORT@", " ORDER BY @SORT@ @DIR@, 1")%>