SELECT COL_NAME AS TYPENAME,
       COL_CODE AS TYPECODE,
       COL_TYPECODE AS APPBASECODE,
       COL_SEARCHTYPE AS SEARCHTYPE,
       COL_DATATYPEPARENTDATATYPE AS ISPARENT
  FROM TBL_DICT_DATATYPE
 WHERE     (:IsDeleted IS NULL OR NVL (col_isdeleted, 0) = :IsDeleted)
       AND (:IsParent IS NULL OR NVL (col_datatypeparentdatatype, 0) = 0)