SELECT COL_ERRORMESSAGE AS ERRORMESSAGE,
       COL_TYPE AS TYPE,
       COL_APPBASECODE AS APPBASECODE
FROM TBL_DOM_MODELJOURNAL
WHERE COL_MDM_MODVERDOM_MODJRNL =
          (SELECT MAX (COL_ID)
             FROM TBL_MDM_MODELVERSION
            WHERE COL_MDM_MODELVERSIONMDM_MODEL = :MODEL_ID)
       AND COL_ERRORCODE IS NOT NULL
       AND COL_ERRORMESSAGE IS NOT NULL