DECLARE
  v_StateId NUMBER;
  v_DelStateRecord VARCHAR2(255);

BEGIN
  v_StateId := :StateId;
  v_DelStateRecord := :DelStateRecord;

  --arp sla
  DELETE  FROM TBL_AUTORULEPARAMTMPL
  WHERE COL_DICT_STATESLAACTIONARP IN
    (SELECT COL_ID 
     FROM TBL_DICT_STATESLAACTION
     WHERE COL_STATESLAACTNSTATESLAEVNT IN
      (SELECT COL_ID 
       FROM TBL_DICT_STATESLAEVENT
       WHERE COL_STATESLAEVENTDICT_STATE=v_StateId));

  --arp events
  DELETE FROM TBL_AUTORULEPARAMTMPL
  WHERE COL_AUTORULEPARTMPLSTATEEVENT IN
    (SELECT COL_ID 
     FROM TBL_DICT_STATEEVENT
     WHERE COL_STATEEVENTSTATE=v_StateId);

  --sla actions
  DELETE FROM TBL_DICT_STATESLAACTION
  WHERE COL_STATESLAACTNSTATESLAEVNT IN
    (SELECT COL_ID 
     FROM TBL_DICT_STATESLAEVENT
     WHERE COL_STATESLAEVENTDICT_STATE=v_StateId);
  
  --sla events    
  DELETE FROM TBL_DICT_STATESLAEVENT
  WHERE COL_STATESLAEVENTDICT_STATE=v_StateId;
  
  --state events
  DELETE FROM TBL_DICT_STATEEVENT
  WHERE COL_STATEEVENTSTATE=v_StateId;
  
  --transitions
  DELETE FROM TBL_DICT_TRANSITION
  WHERE COL_SOURCETRANSITIONSTATE=v_StateId;
  
  DELETE FROM TBL_DICT_TRANSITION    
  WHERE COL_TARGETTRANSITIONSTATE=v_StateId; 

  IF v_DelStateRecord IS NOT NULL THEN
  --state
    DELETE FROM TBL_DICT_STATE
    WHERE COL_ID=v_StateId;
  END IF;


END;