SELECT CT.COL_ID AS ID,
       CT.COL_CUSTOMDATAPROCESSOR AS CUSTOMDATAPROCESSOR,
       CT.COL_UPDATECUSTDATAPROCESSOR AS UPDATECUSTDATAPROCESSOR,
       CT.COL_PROCESSORCODE AS PROCESSORCODE,
       CT.COL_RETCUSTDATAPROCESSOR AS RETCUSTDATAPROCESSOR,
       CT.COL_CUSTOMVALIDATOR AS CUSTOMVALIDATOR,
       CT.COL_CUSTOMVALRESULTPROCESSOR AS CUSTOMVALRESULTPROCESSOR,
       CT.COL_CUSTOMCOUNTDATAPROCESSOR AS CUSTOMCOUNTDATAPROCESSOR,
       CT.COL_CODE AS CODE,
       CT.COL_COLORCODE AS COLORCODE,
       CT.COL_DESCRIPTION AS DESCRIPTION,
       CT.COL_NAME AS NAME,
       CT.COL_SHOWINPORTAL AS SHOWINPORTAL,
       CT.COL_ISDELETED AS ISDELETED,
       CT.COL_ISDRAFTMODEAVAIL AS ISDRAFTMODEAVAIL,
       CT.COL_DEBUGMODE AS DEBUGMODE,
       CT.COL_DEFAULTDOCFOLDER AS DEFAULTDOCFOLDER,
       CT.COL_DEFAULTPORTALDOCFOLDER AS DEFAULTPORTALDOCFOLDER,
       CT.COL_DEFAULTMAILFOLDER AS DEFAULTMAILFOLDER,
       CT.COL_CASETYPEPRIORITY AS PRIORITY_ID,
       CASE
         WHEN NVL(CT.COL_CASETYPEPRIORITY, 0) = 0 THEN
          (SELECT COL_ID FROM TBL_STP_PRIORITY WHERE COL_ISDEFAULT = 1)
         ELSE
          CT.COL_CASETYPEPRIORITY
       END AS DEFAULT_PRIORITY_ID,
       SC.COL_ID AS STATECONFIG_ID,
       SC.COL_NAME AS STATECONFIG_NAME,
       SC_DEF.STATECONFIG_ID AS DEFAULTSTATECONFIG_ID,
       MST.COL_ID AS MILESTONE_ID,
       MST.COL_NAME AS MILESTONE_NAME,
       CT.COL_ICONCODE AS ICONCODE,
       CT.COL_USEDATAMODEL AS USEDATAMODEL,
       R.OBJECTID AS ROOTOBJECTID,
       R.OBJECTCODE AS ROOTOBJECTCODE,
       AP.MDM_FORM AS CREATEFORMID,
       (SELECT LIST_COLLECT(CAST(COLLECT(TO_CHAR(RC.COL_NAME) ORDER BY TO_CHAR(RC.COL_NAME)) AS SPLIT_TBL), ', ', 1) AS IDS
          FROM TBL_STP_RESOLUTIONCODE RC
         INNER JOIN TBL_CASESYSTYPERESOLUTIONCODE CTRC
            ON RC.COL_ID = CTRC.col_casetyperesolutioncode
         WHERE CT.COL_ID = CTRC.COL_TBL_DICT_CASESYSTYPE) AS RESOLUTIONCODES_NAMES,
       (SELECT LIST_COLLECT(CAST(COLLECT(TO_CHAR(RC.COL_ID) ORDER BY TO_CHAR(RC.COL_ID)) AS SPLIT_TBL), '|||', 1) AS IDS
          FROM TBL_STP_RESOLUTIONCODE RC
         INNER JOIN TBL_CASESYSTYPERESOLUTIONCODE CTRC
            ON RC.COL_ID = CTRC.col_casetyperesolutioncode
         WHERE CT.COL_ID = CTRC.COL_TBL_DICT_CASESYSTYPE) AS RESOLUTIONCODES_IDS,
       F_DCM_GETPROCEDURECASETYPE(CASESYSTYPEID => CT.COL_ID, PROCEDUREID => NULL) AS PROCEDURE_ID,
       F_GETNAMEFROMACCESSSUBJECT(CT.COL_CREATEDBY) AS CREATEDBY_NAME,
       F_UTIL_GETDRTNFRMNOW(CT.COL_CREATEDDATE) AS CREATEDDURATION,
       F_GETNAMEFROMACCESSSUBJECT(CT.COL_MODIFIEDBY) AS MODIFIEDBY_NAME,
       F_UTIL_GETDRTNFRMNOW(CT.COL_MODIFIEDDATE) AS MODIFIEDDURATION,
       P.COL_NAME AS PROCEDURE_NAME,
       M.COL_ID AS DATAMODEL_ID,
       M.COL_NAME AS DATAMODEL_NAME
  FROM TBL_DICT_CASESYSTYPE CT
  LEFT JOIN (SELECT CT.COL_ID AS MDM_MODEL_CASETYPE, DO.COL_ID AS OBJECTID, DO.COL_CODE AS OBJECTCODE
               FROM TBL_MDM_MODEL MD
              INNER JOIN TBL_DOM_MODEL DM
                 ON DM.COL_DOM_MODELMDM_MODEL = MD.COL_ID
              INNER JOIN TBL_DOM_OBJECT DO
                 ON DM.COL_ID = DO.COL_DOM_OBJECTDOM_MODEL
              INNER JOIN TBL_DICT_CASESYSTYPE CT
                 ON ct.col_casesystypemodel = MD.col_id
              WHERE UPPER(DO.COL_TYPE) = 'ROOTBUSINESSOBJECT') R
    ON R.MDM_MODEL_CASETYPE = CT.COL_ID
  LEFT JOIN VW_DCM_ASSOCPAGE AP
    ON AP.CASESYSTYPE = CT.COL_ID
   AND AP.PAGETYPE_CODE = 'MDM_CREATE_FORM'
  LEFT JOIN TBL_DICT_STATECONFIG SC
    ON SC.COL_ID = CT.COL_STATECONFIGCASESYSTYPE
  LEFT JOIN (SELECT COL_ID AS STATECONFIG_ID, COL_NAME AS STATECONFIG_NAME
               FROM TBL_DICT_STATECONFIG
              WHERE NVL(COL_ISDEFAULT, 0) = 1
                AND NVL(COL_ISDELETED, 0) = 0
                AND (UPPER(COL_TYPE) = 'CASE')) SC_DEF
    ON 1 = 1
  LEFT JOIN TBL_DICT_STATECONFIG MST
    ON MST.COL_ISCURRENT = 1
   AND MST.COL_CASESYSTYPESTATECONFIG = CT.COL_ID
  LEFT JOIN TBL_PROCEDURE P
    ON P.COL_ID = ct.COL_CASESYSTYPEPROCEDURE
  LEFT JOIN TBL_MDM_MODEL M
    ON M.COL_ID = ct.COL_CASESYSTYPEMODEL
   AND M.COL_USEDFOR = 'CASE_TYPE'
 WHERE (:CASETYPE_ID IS NULL OR CT.COL_ID = :CASETYPE_ID)
   AND (:EXCLUDE_CT_ID IS NULL OR CT.COL_ID != :EXCLUDE_CT_ID)
   AND (:PARENT_ID IS NULL OR CT.COL_ID IN (SELECT COL_CASELINKTMPLCHILDCASETYPE
                                              FROM TBL_CASELINKTMPL
                                             WHERE COL_CASELINKTMPLPRNTCASETYPE = :PARENT_ID
                                             GROUP BY COL_CASELINKTMPLCHILDCASETYPE))
   AND (:UNIFIED_SEARCH IS NULL OR LOWER(CT.COL_CODE) LIKE F_UTIL_TOWILDCARDS(:UNIFIED_SEARCH) OR
       LOWER(CT.COL_NAME) LIKE F_UTIL_TOWILDCARDS(:UNIFIED_SEARCH) OR LOWER(CT.COL_DESCRIPTION) LIKE F_UTIL_TOWILDCARDS(:UNIFIED_SEARCH))
   AND (:PSEARCH IS NULL OR (LOWER(CT.col_name) LIKE LOWER('%' || :PSEARCH || '%')))
   AND (:ISDATAMODEL IS NULL OR (NVL(M.COL_ID, 0) <> 0))

-- need use DCM_getCaseTypes
-- AND (F_dcm_iscasetypecreatealwms(accessobjectid => (SELECT id FROM TABLE(F_dcm_getcasetypeaolist()) WHERE  casetypeid = CT.COL_ID)) = 1)
<%=IFNOTNULL("@SORT@", " ORDER BY DECODE( UPPER('@SORT@'),'ID',ID,'DATAMODEL_ID',DATAMODEL_ID,'PROCEDURE_ID',PROCEDURE_ID,'CREATEDDURATION',CREATEDDURATION,'MODIFIEDDURATION',MODIFIEDDURATION) @DIR@, UPPER(@SORT@) @DIR@")%>