DECLARE
	--input
	v_case_id integer;
	v_task_id integer;

BEGIN	
	--system
	:ErrorCode := 0;
	:ErrorMessage := '';
	

	--PRIORITIES vs CASE TYPES
	OPEN :CUR_PRIORITIESCASETYPES FOR
		SELECT   COL_STP_PRIORITYCASE as PRIORITY_ID,
		COL_CASEDICT_CASESYSTYPE as CASETYPE_ID,
		COUNT(1) as TOTAL_COUNT
		FROM     tbl_Case
		GROUP BY COL_STP_PRIORITYCASE, COL_CASEDICT_CASESYSTYPE;
	
	--REFERENCE DATA
	OPEN :CUR_PRIORITIES FOR
		SELECT 
		COL_ID as PRIORITY_ID,
		COL_NAME as PRIORITY_NAME,
		COL_CODE as PRIORITY_CODE,
		COL_VALUE as PRIORITY_VALUE
		FROM tbl_STP_Priority;
		
	OPEN :CUR_CASETYPES FOR
		SELECT 
		COL_ID as CASETYPE_ID,
		COL_NAME as CASETYPE_NAME,
		COL_CODE as CASETYPE_CODE
		FROM tbl_DICT_CaseSysType;
END;