SELECT 
    l.COL_ID AS ID,
    l.COL_ISDEFAULT AS ISDEFAULT,
    l.COL_APPBASELANGID AS APPBASELANGID,
    l.COL_LANGUAGENAME AS LANGUAGENAME,
    l.COL_LANGUAGECODE AS LANGUAGECODE,
    l.COL_ISDELETED AS ISDELETED,
    l.COL_EXTCODE AS EXTCODE,
    l.COL_MOMENTCODE AS MOMENTCODE,
    l.COL_PLURALFORMID AS PLURALFORMID,
    p.COL_LANGUAGE AS PLURALCODE,
    p.COL_PLURALFORMS AS PLURALFORMS,
    f_getNameFromAccessSubject(l.COL_CREATEDBY) AS CreatedBy_Name,
    f_UTIL_getDrtnFrmNow(l.COL_CREATEDDATE) AS CreatedDuration,
    f_getNameFromAccessSubject(l.COL_MODIFIEDBY) AS ModifiedBy_Name,
    f_UTIL_getDrtnFrmNow(l.COL_MODIFIEDDATE) AS ModifiedDuration
    FROM TBL_LOC_LANGUAGES l
    	LEFT JOIN TBL_LOC_PLURALFORM p ON p.COL_ID = l.COL_PLURALFORMID
WHERE (:ID IS NULL OR l.COL_ID = :ID)
	and (:LANGUAGECODE IS NULL OR l.COL_LANGUAGECODE = :LANGUAGECODE)
    and (:ISDEFAULT IS NULL OR nvl(l.COL_ISDEFAULT, 0) = 1)